#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

cache = false
strict_mode = true
separator_aware = true
dir_length = 2
sort_order = ["config", "tmux", "zoxide"]
blacklist = ["codex-fish-test"]

[default_session]

[[session]]
name = "main"
path = "/Users/alfredo.vasquez"

[[session]]
name = "brain"
path = "/Users/alfredo.vasquez/brain"

[[session]]
name = "kigo-enforcement"
path = "/Users/alfredo.vasquez/dev/work/Kigo/kigo-enforcement"
windows = ["ai", "git", "editor", "sql", "http", "build"]

[[session]]
name = "kigo-lpr-cams"
path = "/Users/alfredo.vasquez/dev/work/Kigo/kigo-lpr/kigo-lpr-cams"
windows = ["ai", "git", "editor", "sql", "http", "build"]

[[session]]
name = "kigo-lpr-gateway"
path = "/Users/alfredo.vasquez/dev/work/Kigo/kigo-lpr/kigo-lpr-gateway"
windows = ["ai", "git", "editor", "sql", "http", "build"]

[[session]]
name = "kipuve"
path = "/Users/alfredo.vasquez/dev/work/Kigo/kipuve"
windows = ["ai", "git", "editor", "sql", "http", "build"]

[[session]]
name = "kigo-app-services"
path = "/Users/alfredo.vasquez/dev/work/Kigo/kigo-app-services"
windows = ["ai", "git", "editor", "sql", "http", "build"]

[[session]]
name = "omerxx-dotfiles"
path = "/Users/alfredo.vasquez/dev/personal/Alfredo/omerxx-dotfiles"
windows = ["ai", "git", "editor", "sql", "http", "build"]

[[session]]
name = "id-general"
path = "/Users/alfredo.vasquez/dev/work/Kigo/id-general"
windows = ["ai", "git", "editor", "sql", "http", "build"]

[[session]]
name = "kigo-ddd-planing"
path = "/Users/alfredo.vasquez/dev/work/Kigo/kigo-DDD-planing"
windows = ["ai", "git", "editor", "sql", "http", "build"]

[[window]]
name = "ai"
startup_script = "pi"

[[window]]
name = "git"
startup_script = "lazygit"

[[window]]
name = "editor"
startup_script = "nvim ."

[[window]]
name = "sql"
startup_script = "rainfrog"

[[window]]
name = "http"
startup_script = "atac"

[[window]]
name = "build"

