#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

cache = false
strict_mode = true
separator_aware = true
dir_length = 2
sort_order = ["config", "tmux", "zoxide"]
blacklist = ["codex-fish-test"]

[default_session]

[[session]]
name = "main"
path = "/Users/alfredo.vasquez"

[[session]]
name = "kigo-enforcement"
path = "/Users/alfredo.vasquez/dev/work/Kigo/kigo-enforcement"
windows = ["nvim", "git", "http", "sql", "ai", "docs"]

[[session]]
name = "kigo-lpr-cams"
path = "/Users/alfredo.vasquez/dev/work/Kigo/kigo-lpr/kigo-lpr-cams"
windows = ["nvim", "git", "http", "sql", "ai", "docs"]

[[session]]
name = "kigo-lpr-gateway"
path = "/Users/alfredo.vasquez/dev/work/Kigo/kigo-lpr/kigo-lpr-gateway"
windows = ["nvim", "git", "http", "sql", "ai", "docs"]

[[session]]
name = "kipuve"
path = "/Users/alfredo.vasquez/dev/work/Kigo/kipuve"
windows = ["nvim", "git", "http", "sql", "ai", "docs"]

[[session]]
name = "kigo-app-services"
path = "/Users/alfredo.vasquez/dev/work/Kigo/kigo-app-services"
windows = ["nvim", "git", "http", "sql", "ai", "docs"]

[[session]]
name = "omerxx-dotfiles"
path = "/Users/alfredo.vasquez/dev/personal/Alfredo/omerxx-dotfiles"
windows = ["nvim", "git", "http", "sql", "ai", "docs"]

[[window]]
name = "nvim"
startup_script = "nvim ."

[[window]]
name = "git"
startup_script = "lazygit"

[[window]]
name = "http"
startup_script = "atac"

[[window]]
name = "sql"
startup_script = "rainfrog"

[[window]]
name = "ai"
startup_script = "/Users/alfredo.vasquez/.opencode/bin/opencode"

[[window]]
name = "docs"
path = "/Users/alfredo.vasquez/brain"
startup_script = "nvim ."
